import React, { useState } from 'react';
import { FileText, Share2, Save, MapPin, Clock } from 'lucide-react';
import Card from './ui/Card';
import Button from './ui/Button';
import Input from './ui/Input';

const IncidentReport = ({ selectedState, stateData }) => {
  const [reportData, setReportData] = useState({
    location: '',
    timestamp: new Date().toISOString(),
    description: '',
    officers: '',
    witnesses: '',
    vehicleInfo: ''
  });
  const [recordings, setRecordings] = useState([]);
  const [showShareCard, setShowShareCard] = useState(false);

  const handleInputChange = (field, value) => {
    setReportData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleRecordingComplete = (recordingData) => {
    setRecordings(prev => [...prev, recordingData]);
  };

  const generateShareCard = () => {
    const card = {
      id: `report_${Date.now()}`,
      timestamp: new Date().toLocaleString(),
      state: selectedState ? stateData[selectedState].state : 'Unknown',
      summary: reportData.description.substring(0, 150) + (reportData.description.length > 150 ? '...' : ''),
      location: reportData.location,
      recordings: recordings.length
    };
    
    setShowShareCard(card);
  };

  const shareReport = (method) => {
    const shareText = `Incident Report - ${showShareCard.state}\n` +
                     `Time: ${showShareCard.timestamp}\n` +
                     `Location: ${showShareCard.location}\n` +
                     `Summary: ${showShareCard.summary}\n` +
                     `Generated by LegalShield AI`;
    
    if (method === 'copy') {
      navigator.clipboard.writeText(shareText);
      alert('Report copied to clipboard');
    } else if (method === 'text' && navigator.share) {
      navigator.share({
        title: 'Incident Report',
        text: shareText
      });
    }
  };

  return (
    <div className="w-full max-w-2xl space-y-6">
      <Card variant="glass" className="p-6">
        <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
          <FileText className="w-5 h-5" />
          Incident Report
        </h3>
        
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Input
              label="Location"
              value={reportData.location}
              onChange={(e) => handleInputChange('location', e.target.value)}
              placeholder="Street address or general area"
            />
            <div>
              <label className="block text-sm font-medium mb-2 text-white">
                Time
              </label>
              <div className="flex items-center gap-2 px-3 py-2 border border-white/20 rounded-md bg-white/10 text-white">
                <Clock className="w-4 h-4" />
                <span className="text-sm">{new Date().toLocaleString()}</span>
              </div>
            </div>
          </div>
          
          <div>
            <label className="block text-sm font-medium mb-2 text-white">
              Description of Incident
            </label>
            <textarea
              value={reportData.description}
              onChange={(e) => handleInputChange('description', e.target.value)}
              placeholder="Describe what happened in detail..."
              className="w-full px-3 py-2 h-24 border border-white/20 rounded-md bg-white/10 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-accent resize-none"
            />
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Input
              label="Officer Badge Numbers/Names"
              value={reportData.officers}
              onChange={(e) => handleInputChange('officers', e.target.value)}
              placeholder="If visible or provided"
            />
            <Input
              label="Witnesses Present"
              value={reportData.witnesses}
              onChange={(e) => handleInputChange('witnesses', e.target.value)}
              placeholder="Names or descriptions"
            />
          </div>
          
          <Input
            label="Vehicle Information"
            value={reportData.vehicleInfo}
            onChange={(e) => handleInputChange('vehicleInfo', e.target.value)}
            placeholder="Police car numbers, license plates"
          />
        </div>
      </Card>

      {recordings.length > 0 && (
        <Card variant="glass" className="p-4">
          <h4 className="text-white font-medium mb-3">Recordings ({recordings.length})</h4>
          <div className="space-y-2">
            {recordings.map((recording, index) => (
              <div key={index} className="flex items-center justify-between bg-white/5 rounded p-3">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-accent/20 rounded-full flex items-center justify-center">
                    <FileText className="w-4 h-4 text-accent" />
                  </div>
                  <div>
                    <p className="text-white text-sm">Recording {index + 1}</p>
                    <p className="text-white/60 text-xs">
                      Duration: {Math.floor(recording.duration / 60)}:{(recording.duration % 60).toString().padStart(2, '0')}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      )}

      <div className="flex flex-col sm:flex-row gap-3">
        <Button
          variant="primary"
          className="flex-1"
          onClick={generateShareCard}
          disabled={!reportData.description.trim()}
        >
          <Share2 className="w-4 h-4 mr-2" />
          Generate Share Card
        </Button>
        <Button
          variant="outline"
          className="flex-1"
          onClick={() => alert('Report saved locally (demo)')}
        >
          <Save className="w-4 h-4 mr-2" />
          Save Report
        </Button>
      </div>

      {showShareCard && (
        <Card variant="glass" className="p-6 border-2 border-accent/30">
          <h4 className="text-white font-semibold mb-4">Shareable Report Card</h4>
          
          <div className="bg-white/5 rounded-lg p-4 mb-4">
            <div className="flex items-center gap-2 mb-2">
              <MapPin className="w-4 h-4 text-accent" />
              <span className="text-white font-medium">{showShareCard.state}</span>
            </div>
            <p className="text-white/80 text-sm mb-3">{showShareCard.timestamp}</p>
            <p className="text-white">{showShareCard.summary}</p>
            {showShareCard.recordings > 0 && (
              <p className="text-accent text-sm mt-2">
                {showShareCard.recordings} recording(s) attached
              </p>
            )}
          </div>
          
          <div className="flex gap-2">
            <Button
              variant="primary"
              size="sm"
              onClick={() => shareReport('copy')}
            >
              Copy Link
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => shareReport('text')}
            >
              Share via Text
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
};

export default IncidentReport;